INFO 2024-02-06 19:31:26,146 Watching for file changes with StatReloader
WARNING 2024-02-06 19:31:33,289 Not Found: /r
WARNING 2024-02-06 19:31:33,289 "GET /r HTTP/1.1" 404 2357
INFO 2024-02-06 19:31:36,847 Была вызвана функция coin
INFO 2024-02-06 19:31:36,848 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-06 19:31:38,020 "GET / HTTP/1.1" 200 12
INFO 2024-02-06 19:31:42,017 "GET / HTTP/1.1" 200 12
INFO 2024-02-06 19:31:42,743 "GET / HTTP/1.1" 200 12
INFO 2024-02-06 19:31:44,921 "GET / HTTP/1.1" 200 12
INFO 2024-02-06 19:31:46,497 Была вызвана функция coin
INFO 2024-02-06 19:31:46,497 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-06 19:31:50,595 Была вызвана функция coin
INFO 2024-02-06 19:31:50,595 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-06 19:31:51,447 Была вызвана функция coin
INFO 2024-02-06 19:31:51,448 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-06 19:31:52,027 Была вызвана функция coin
INFO 2024-02-06 19:31:52,027 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-06 19:31:52,597 Была вызвана функция coin
INFO 2024-02-06 19:31:52,598 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-06 19:31:53,223 Была вызвана функция coin
INFO 2024-02-06 19:31:53,224 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-06 19:31:53,746 Была вызвана функция coin
INFO 2024-02-06 19:31:53,747 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-06 19:31:58,100 Была вызвана функция dice
INFO 2024-02-06 19:31:58,101 "GET /random/dice/ HTTP/1.1" 200 43
INFO 2024-02-06 19:32:01,727 Была вызвана функция dice
INFO 2024-02-06 19:32:01,728 "GET /random/dice/ HTTP/1.1" 200 43
INFO 2024-02-06 19:32:02,639 Была вызвана функция dice
INFO 2024-02-06 19:32:02,640 "GET /random/dice/ HTTP/1.1" 200 43
INFO 2024-02-06 19:32:03,322 Была вызвана функция dice
INFO 2024-02-06 19:32:03,323 "GET /random/dice/ HTTP/1.1" 200 43
INFO 2024-02-06 19:32:04,008 Была вызвана функция dice
INFO 2024-02-06 19:32:04,009 "GET /random/dice/ HTTP/1.1" 200 43
INFO 2024-02-06 19:32:07,332 Была вызвана функция dice
INFO 2024-02-06 19:32:07,333 "GET /random/dice/ HTTP/1.1" 200 43
INFO 2024-02-06 19:32:07,716 Была вызвана функция coin
INFO 2024-02-06 19:32:07,717 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-06 19:32:10,155 Была вызвана функция random_num
INFO 2024-02-06 19:32:10,157 "GET /random/random_num/ HTTP/1.1" 200 52
INFO 2024-02-06 19:32:13,642 Была вызвана функция random_num
INFO 2024-02-06 19:32:13,642 "GET /random/random_num/ HTTP/1.1" 200 52
INFO 2024-02-06 19:32:14,187 Была вызвана функция random_num
INFO 2024-02-06 19:32:14,188 "GET /random/random_num/ HTTP/1.1" 200 52
INFO 2024-02-06 19:32:14,821 Была вызвана функция random_num
INFO 2024-02-06 19:32:14,822 "GET /random/random_num/ HTTP/1.1" 200 53
INFO 2024-02-11 16:30:53,223 Watching for file changes with StatReloader
INFO 2024-02-11 16:31:15,803 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-11 16:31:16,675 Watching for file changes with StatReloader
INFO 2024-02-11 16:31:40,222 Watching for file changes with StatReloader
INFO 2024-02-11 16:31:41,755 "GET / HTTP/1.1" 200 12
INFO 2024-02-11 16:31:45,898 "GET / HTTP/1.1" 200 12
INFO 2024-02-11 16:31:47,084 Была вызвана функция random_num
INFO 2024-02-11 16:31:47,085 "GET /random/random_num/ HTTP/1.1" 200 52
INFO 2024-02-11 16:31:53,979 "GET /random/coin HTTP/1.1" 301 0
INFO 2024-02-11 16:31:54,002 Была вызвана функция coin
INFO 2024-02-11 16:31:54,003 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 16:32:45,598 Была вызвана функция coin
INFO 2024-02-11 16:32:45,599 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:34:09,807 Была вызвана функция coin
INFO 2024-02-11 16:34:09,808 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:34:10,720 Была вызвана функция coin
INFO 2024-02-11 16:34:10,720 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:34:11,544 Была вызвана функция coin
INFO 2024-02-11 16:34:11,545 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:34:12,392 Была вызвана функция coin
INFO 2024-02-11 16:34:12,393 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:34:13,126 Была вызвана функция coin
INFO 2024-02-11 16:34:13,127 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:34:15,039 Была вызвана функция coin
INFO 2024-02-11 16:34:15,039 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 16:42:55,731 Watching for file changes with StatReloader
INFO 2024-02-11 16:43:01,004 Была вызвана функция coin
INFO 2024-02-11 16:43:01,005 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 16:43:02,088 Была вызвана функция coin
INFO 2024-02-11 16:43:02,088 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 16:43:04,324 Была вызвана функция coin
INFO 2024-02-11 16:43:04,324 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 16:43:06,053 Была вызвана функция coin
INFO 2024-02-11 16:43:06,053 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:45:00,932 Watching for file changes with StatReloader
INFO 2024-02-11 16:45:24,022 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-11 16:45:25,282 Watching for file changes with StatReloader
INFO 2024-02-11 16:45:34,867 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-11 16:45:35,519 Watching for file changes with StatReloader
INFO 2024-02-11 16:45:46,938 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-11 16:45:47,491 Watching for file changes with StatReloader
INFO 2024-02-11 16:45:52,135 Была вызвана функция coin
INFO 2024-02-11 16:45:52,136 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:45:53,493 Была вызвана функция coin
INFO 2024-02-11 16:45:53,494 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 16:46:41,637 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/models.py changed, reloading.
INFO 2024-02-11 16:46:55,027 Watching for file changes with StatReloader
INFO 2024-02-11 16:48:02,687 Watching for file changes with StatReloader
INFO 2024-02-11 16:51:41,356 Watching for file changes with StatReloader
INFO 2024-02-11 16:51:45,275 Была вызвана функция coin
INFO 2024-02-11 16:51:45,276 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:51:45,949 Была вызвана функция coin
INFO 2024-02-11 16:51:45,950 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:51:46,745 Была вызвана функция coin
INFO 2024-02-11 16:51:46,746 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 16:51:47,545 Была вызвана функция coin
INFO 2024-02-11 16:51:47,546 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 16:51:48,282 Была вызвана функция coin
INFO 2024-02-11 16:51:48,283 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 16:51:49,053 Была вызвана функция coin
INFO 2024-02-11 16:51:49,054 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 16:51:50,224 Была вызвана функция coin
INFO 2024-02-11 16:51:50,224 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 17:22:44,444 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/models.py changed, reloading.
INFO 2024-02-11 17:22:46,421 Watching for file changes with StatReloader
INFO 2024-02-11 17:22:50,008 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/models.py changed, reloading.
INFO 2024-02-11 17:34:12,803 Watching for file changes with StatReloader
INFO 2024-02-11 17:34:16,578 Была вызвана функция coin
INFO 2024-02-11 17:34:16,579 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-11 17:34:25,266 Была вызвана функция coin
INFO 2024-02-11 17:34:25,266 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-11 17:34:53,900 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-11 17:34:55,469 Watching for file changes with StatReloader
ERROR 2024-02-11 17:35:01,138 Internal Server Error: /random/statistic/5
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 42, in statistic
    return HttpResponse(coin.get_last_n_flip(n))
AttributeError: 'function' object has no attribute 'get_last_n_flip'
ERROR 2024-02-11 17:35:01,139 "GET /random/statistic/5 HTTP/1.1" 500 58084
INFO 2024-02-11 17:36:14,898 Watching for file changes with StatReloader
ERROR 2024-02-11 17:36:17,019 Internal Server Error: /random/statistic/5
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 42, in statistic
    return HttpResponse(Coin.get_last_n_flip(n))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/models.py", line 10, in get_last_n_flip
    flips = Coin.objects.all()[-n:]
TypeError: bad operand type for unary -: 'str'
ERROR 2024-02-11 17:36:17,020 "GET /random/statistic/5 HTTP/1.1" 500 61390
INFO 2024-02-11 17:36:50,310 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-11 17:36:51,130 Watching for file changes with StatReloader
INFO 2024-02-11 17:37:51,191 Watching for file changes with StatReloader
ERROR 2024-02-11 17:37:54,107 Internal Server Error: /random/statistic/5
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 42, in statistic
    return HttpResponse(Coin.get_last_n_flip(n))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/models.py", line 10, in get_last_n_flip
    flips = Coin.objects.all()[-n:]
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 431, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2024-02-11 17:37:54,109 "GET /random/statistic/5 HTTP/1.1" 500 65715
INFO 2024-02-11 17:39:39,277 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/models.py changed, reloading.
INFO 2024-02-11 17:39:40,097 Watching for file changes with StatReloader
INFO 2024-02-11 17:39:42,308 "GET /random/statistic/5 HTTP/1.1" 200 18
INFO 2024-02-11 17:39:45,700 "GET /random/statistic/5 HTTP/1.1" 200 18
INFO 2024-02-11 17:40:40,816 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-11 17:40:42,377 Watching for file changes with StatReloader
INFO 2024-02-11 17:40:43,408 "GET /random/statistic/5 HTTP/1.1" 200 69
INFO 2024-02-11 17:42:16,159 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-11 17:42:17,707 Watching for file changes with StatReloader
INFO 2024-02-11 17:42:18,725 "GET /random/statistic/5 HTTP/1.1" 200 69
INFO 2024-02-11 17:42:30,601 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-11 17:42:31,166 Watching for file changes with StatReloader
INFO 2024-02-11 17:42:33,233 "GET /random/statistic/5 HTTP/1.1" 200 33
INFO 2024-02-11 17:43:00,997 "GET /random/statistic/5 HTTP/1.1" 200 33
WARNING 2024-02-11 17:43:01,352 Not Found: /favicon.ico
WARNING 2024-02-11 17:43:01,352 "GET /favicon.ico HTTP/1.1" 404 2387
INFO 2024-02-11 17:44:41,591 "GET /random/statistic/5 HTTP/1.1" 200 33
INFO 2024-02-11 17:44:42,512 "GET /random/statistic/5 HTTP/1.1" 200 33
INFO 2024-02-11 17:44:45,220 "GET /random/statistic/3 HTTP/1.1" 200 33
INFO 2024-02-11 17:44:48,196 "GET /random/statistic/1 HTTP/1.1" 200 34
INFO 2024-02-11 17:44:51,458 "GET /random/statistic/5 HTTP/1.1" 200 33
INFO 2024-02-11 17:47:52,778 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/models.py changed, reloading.
INFO 2024-02-11 17:47:54,230 Watching for file changes with StatReloader
INFO 2024-02-11 17:47:57,117 "GET /random/statistic/5 HTTP/1.1" 200 32
INFO 2024-02-11 17:47:57,951 "GET /random/statistic/5 HTTP/1.1" 200 32
INFO 2024-02-11 17:48:00,788 "GET /random/statistic/3 HTTP/1.1" 200 32
INFO 2024-02-11 17:48:02,936 "GET /random/statistic/30 HTTP/1.1" 200 34
INFO 2024-02-11 17:48:10,618 "GET /random/statistic/26 HTTP/1.1" 200 34
INFO 2024-02-11 17:48:14,075 "GET /random/statistic/10 HTTP/1.1" 200 32
INFO 2024-02-16 21:02:01,225 Watching for file changes with StatReloader
WARNING 2024-02-16 21:02:06,962 Not Found: /les3/post/50/
WARNING 2024-02-16 21:02:06,964 "GET /les3/post/50/ HTTP/1.1" 404 2393
WARNING 2024-02-16 21:02:08,368 Not Found: /les3/author/5/
WARNING 2024-02-16 21:02:08,368 "GET /les3/author/5/ HTTP/1.1" 404 2396
WARNING 2024-02-16 21:02:08,530 Not Found: /l
WARNING 2024-02-16 21:02:08,531 "GET /l HTTP/1.1" 404 2357
INFO 2024-02-16 21:02:11,038 "GET / HTTP/1.1" 200 12
INFO 2024-02-16 21:02:15,538 "GET / HTTP/1.1" 200 12
WARNING 2024-02-16 21:02:17,053 Not Found: /coin
WARNING 2024-02-16 21:02:17,053 "GET /coin HTTP/1.1" 404 2366
INFO 2024-02-16 21:02:27,615 "GET / HTTP/1.1" 200 12
INFO 2024-02-16 21:02:28,602 Была вызвана функция coin
INFO 2024-02-16 21:02:28,603 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-16 21:09:39,617 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-16 21:09:40,758 Watching for file changes with StatReloader
INFO 2024-02-16 21:15:22,380 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:15:23,740 Watching for file changes with StatReloader
INFO 2024-02-16 21:16:45,999 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:16:46,869 Watching for file changes with StatReloader
INFO 2024-02-16 21:18:11,611 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:18:12,707 Watching for file changes with StatReloader
INFO 2024-02-16 21:19:19,942 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:19:20,965 Watching for file changes with StatReloader
INFO 2024-02-16 21:20:12,088 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:20:13,137 Watching for file changes with StatReloader
INFO 2024-02-16 21:21:35,795 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:21:37,245 Watching for file changes with StatReloader
INFO 2024-02-16 21:22:06,101 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:22:07,037 Watching for file changes with StatReloader
INFO 2024-02-16 21:22:16,484 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:22:17,395 Watching for file changes with StatReloader
INFO 2024-02-16 21:22:28,914 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:22:29,522 Watching for file changes with StatReloader
INFO 2024-02-16 21:23:09,354 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:23:10,440 Watching for file changes with StatReloader
INFO 2024-02-16 21:23:48,399 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:23:49,619 Watching for file changes with StatReloader
INFO 2024-02-16 21:24:53,633 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:24:54,439 Watching for file changes with StatReloader
INFO 2024-02-16 21:25:43,674 Была вызвана функция coin
INFO 2024-02-16 21:25:43,674 "GET /random/coin/5 HTTP/1.1" 200 245
INFO 2024-02-16 21:25:59,378 Была вызвана функция coin
INFO 2024-02-16 21:25:59,381 "GET /random/coin/ HTTP/1.1" 200 151
INFO 2024-02-16 21:26:02,681 Была вызвана функция coin
INFO 2024-02-16 21:26:02,682 "GET /random/coin/5 HTTP/1.1" 200 243
INFO 2024-02-16 21:27:46,496 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:27:47,506 Watching for file changes with StatReloader
INFO 2024-02-16 21:27:48,364 Была вызвана функция coin
INFO 2024-02-16 21:27:48,365 "GET /random/coin/5 HTTP/1.1" 200 241
INFO 2024-02-16 21:27:50,293 Была вызвана функция coin
INFO 2024-02-16 21:27:50,294 "GET /random/coin/ HTTP/1.1" 200 6
INFO 2024-02-16 21:28:12,227 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:28:13,032 Watching for file changes with StatReloader
INFO 2024-02-16 21:28:13,263 Была вызвана функция coin
INFO 2024-02-16 21:28:13,264 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-16 21:28:14,079 Была вызвана функция coin
INFO 2024-02-16 21:28:14,079 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-16 21:28:14,682 Была вызвана функция coin
INFO 2024-02-16 21:28:14,682 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-16 21:28:15,198 Была вызвана функция coin
INFO 2024-02-16 21:28:15,198 "GET /random/coin/ HTTP/1.1" 200 10
INFO 2024-02-16 21:28:18,526 Была вызвана функция coin
INFO 2024-02-16 21:28:18,527 "GET /random/coin/10 HTTP/1.1" 200 357
INFO 2024-02-16 21:29:27,686 Была вызвана функция coin
INFO 2024-02-16 21:29:27,688 "GET /random/coin/0 HTTP/1.1" 200 129
INFO 2024-02-16 21:31:35,697 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:31:37,706 Watching for file changes with StatReloader
INFO 2024-02-16 21:32:10,787 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:32:14,474 Watching for file changes with StatReloader
INFO 2024-02-16 21:33:05,230 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-16 21:33:06,358 Watching for file changes with StatReloader
INFO 2024-02-16 21:35:32,689 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:35:33,975 Watching for file changes with StatReloader
INFO 2024-02-16 21:36:07,604 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:36:08,479 Watching for file changes with StatReloader
INFO 2024-02-16 21:40:07,734 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:40:09,066 Watching for file changes with StatReloader
WARNING 2024-02-16 21:40:11,260 Not Found: /random/coin_pd
WARNING 2024-02-16 21:40:11,261 "GET /random/coin_pd HTTP/1.1" 404 3388
ERROR 2024-02-16 21:40:33,212 Internal Server Error: /random/coin_pd/3
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 17, in wrapper
    result = func(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 52, in coin_pd
    df = pd.DataFrame(result).to_html()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 875, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
ERROR 2024-02-16 21:40:33,216 "GET /random/coin_pd/3 HTTP/1.1" 500 68501
ERROR 2024-02-16 21:40:46,919 Internal Server Error: /random/coin_pd/3
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 17, in wrapper
    result = func(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 52, in coin_pd
    df = pd.DataFrame(result).to_html()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 875, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
ERROR 2024-02-16 21:40:46,921 "GET /random/coin_pd/3 HTTP/1.1" 500 68499
INFO 2024-02-16 21:40:47,708 Была вызвана функция coin
INFO 2024-02-16 21:40:47,714 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-16 21:40:48,339 Была вызвана функция coin
INFO 2024-02-16 21:40:48,340 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-16 21:42:09,287 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:42:10,323 Watching for file changes with StatReloader
INFO 2024-02-16 21:42:36,024 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:42:36,803 Watching for file changes with StatReloader
INFO 2024-02-16 21:42:38,176 Была вызвана функция coin_pd
INFO 2024-02-16 21:42:38,177 "GET /random/coin_pd/3 HTTP/1.1" 200 839
INFO 2024-02-16 21:45:20,833 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:45:21,957 Watching for file changes with StatReloader
ERROR 2024-02-16 21:45:23,185 Internal Server Error: /random/coin_pd/3
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 17, in wrapper
    result = func(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 51, in coin_pd
    result_lst.append({'Попытка': i + 1, 'результат': {random.choice(side)}})
NameError: name 'result_lst' is not defined
ERROR 2024-02-16 21:45:23,186 "GET /random/coin_pd/3 HTTP/1.1" 500 63077
INFO 2024-02-16 21:45:32,165 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:45:32,707 Watching for file changes with StatReloader
INFO 2024-02-16 21:45:35,387 Была вызвана функция coin_pd
INFO 2024-02-16 21:45:35,388 "GET /random/coin_pd/3 HTTP/1.1" 200 837
INFO 2024-02-16 21:47:20,648 Watching for file changes with StatReloader
INFO 2024-02-16 21:47:23,142 Была вызвана функция coin_pd
INFO 2024-02-16 21:47:23,142 "GET /random/coin_pd/3 HTTP/1.1" 200 837
INFO 2024-02-16 21:49:17,208 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:49:18,139 Watching for file changes with StatReloader
INFO 2024-02-16 21:49:22,328 Была вызвана функция coin_pd
INFO 2024-02-16 21:49:22,330 "GET /random/coin_pd/3 HTTP/1.1" 200 833
INFO 2024-02-16 21:51:50,729 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:51:51,796 Watching for file changes with StatReloader
INFO 2024-02-16 21:51:53,328 Была вызвана функция coin_pd
ERROR 2024-02-16 21:51:53,382 Internal Server Error: /random/coin_pd/3
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view randomapp.views.wrapper didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 21:51:53,383 "GET /random/coin_pd/3 HTTP/1.1" 500 59788
INFO 2024-02-16 21:52:04,655 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:52:05,589 Watching for file changes with StatReloader
INFO 2024-02-16 21:52:06,434 Была вызвана функция coin_pd
ERROR 2024-02-16 21:52:06,474 Internal Server Error: /random/coin_pd/3
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view randomapp.views.wrapper didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 21:52:06,475 "GET /random/coin_pd/3 HTTP/1.1" 500 59788
INFO 2024-02-16 21:52:07,577 Была вызвана функция coin_pd
ERROR 2024-02-16 21:52:07,610 Internal Server Error: /random/coin_pd/3
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view randomapp.views.wrapper didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 21:52:07,611 "GET /random/coin_pd/3 HTTP/1.1" 500 59788
INFO 2024-02-16 21:52:43,956 Была вызвана функция coin_pd
ERROR 2024-02-16 21:52:44,013 Internal Server Error: /random/coin_pd/3
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view randomapp.views.wrapper didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 21:52:44,015 "GET /random/coin_pd/3 HTTP/1.1" 500 59788
INFO 2024-02-16 21:52:46,047 Была вызвана функция coin_pd
ERROR 2024-02-16 21:52:46,076 Internal Server Error: /random/coin_pd/2
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view randomapp.views.wrapper didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 21:52:46,077 "GET /random/coin_pd/2 HTTP/1.1" 500 59788
INFO 2024-02-16 21:53:41,696 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:53:42,525 Watching for file changes with StatReloader
INFO 2024-02-16 21:53:45,329 Была вызвана функция coin_pd
ERROR 2024-02-16 21:53:45,469 Internal Server Error: /random/coin_pd/2
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view randomapp.views.wrapper didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 21:53:45,470 "GET /random/coin_pd/2 HTTP/1.1" 500 59788
INFO 2024-02-16 21:54:29,730 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:54:30,698 Watching for file changes with StatReloader
INFO 2024-02-16 21:54:32,137 Была вызвана функция coin_pd
ERROR 2024-02-16 21:54:32,188 Internal Server Error: /random/coin_pd/2
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view randomapp.views.wrapper didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 21:54:32,189 "GET /random/coin_pd/2 HTTP/1.1" 500 59788
INFO 2024-02-16 21:54:55,518 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:54:56,415 Watching for file changes with StatReloader
INFO 2024-02-16 21:54:57,561 Была вызвана функция coin_pd
INFO 2024-02-16 21:54:57,562 "GET /random/coin_pd/2 HTTP/1.1" 200 690
INFO 2024-02-16 21:55:20,364 Была вызвана функция coin_pd
INFO 2024-02-16 21:55:20,376 "GET /random/coin_pd/2 HTTP/1.1" 200 690
WARNING 2024-02-16 21:55:20,587 Not Found: /favicon.ico
WARNING 2024-02-16 21:55:20,588 "GET /favicon.ico HTTP/1.1" 404 2387
INFO 2024-02-16 21:57:39,857 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:57:41,253 Watching for file changes with StatReloader
INFO 2024-02-16 21:58:48,850 Была вызвана функция coin_pd
INFO 2024-02-16 21:58:48,852 "GET /random/coin_pd/2 HTTP/1.1" 200 480
INFO 2024-02-16 21:59:20,267 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:59:21,395 Watching for file changes with StatReloader
INFO 2024-02-16 21:59:30,716 Была вызвана функция coin_pd
INFO 2024-02-16 21:59:30,717 "GET /random/coin_pd/2 HTTP/1.1" 200 496
INFO 2024-02-16 21:59:32,115 Была вызвана функция coin_pd
INFO 2024-02-16 21:59:32,116 "GET /random/coin_pd/2 HTTP/1.1" 200 498
INFO 2024-02-16 21:59:32,832 Была вызвана функция coin_pd
INFO 2024-02-16 21:59:32,833 "GET /random/coin_pd/2 HTTP/1.1" 200 498
INFO 2024-02-16 21:59:33,719 Была вызвана функция coin_pd
INFO 2024-02-16 21:59:33,720 "GET /random/coin_pd/2 HTTP/1.1" 200 496
INFO 2024-02-16 21:59:34,487 Была вызвана функция coin_pd
INFO 2024-02-16 21:59:34,488 "GET /random/coin_pd/2 HTTP/1.1" 200 496
INFO 2024-02-16 21:59:35,100 Была вызвана функция coin_pd
INFO 2024-02-16 21:59:35,101 "GET /random/coin_pd/2 HTTP/1.1" 200 498
INFO 2024-02-16 21:59:39,444 Была вызвана функция coin_pd
INFO 2024-02-16 21:59:39,446 "GET /random/coin_pd/10 HTTP/1.1" 200 1123
INFO 2024-02-16 21:59:53,485 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 21:59:54,409 Watching for file changes with StatReloader
INFO 2024-02-16 21:59:56,740 Была вызвана функция coin_pd
INFO 2024-02-16 21:59:56,741 "GET /random/coin_pd/10 HTTP/1.1" 200 1119
WARNING 2024-02-16 21:59:58,788 Not Found: /random/coin_pd/
WARNING 2024-02-16 21:59:58,790 "GET /random/coin_pd/ HTTP/1.1" 404 3391
INFO 2024-02-16 22:01:00,402 Была вызвана функция coin_pd
INFO 2024-02-16 22:01:00,403 "GET /random/coin_pd/0 HTTP/1.1" 200 276
WARNING 2024-02-16 22:01:04,084 Not Found: /random/coin_pd/
WARNING 2024-02-16 22:01:04,084 "GET /random/coin_pd/ HTTP/1.1" 404 3391
INFO 2024-02-16 22:01:22,762 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 22:01:24,564 Watching for file changes with StatReloader
WARNING 2024-02-16 22:01:25,989 Not Found: /random/coin_pd/
WARNING 2024-02-16 22:01:25,990 "GET /random/coin_pd/ HTTP/1.1" 404 3391
INFO 2024-02-16 22:01:29,602 Была вызвана функция coin_pd
INFO 2024-02-16 22:01:29,604 "GET /random/coin_pd/5 HTTP/1.1" 200 731
INFO 2024-02-16 22:03:10,782 "GET /random/coin HTTP/1.1" 301 0
INFO 2024-02-16 22:03:10,800 Была вызвана функция coin
INFO 2024-02-16 22:03:10,801 "GET /random/coin/ HTTP/1.1" 200 8
INFO 2024-02-16 22:04:51,168 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 22:04:51,998 Watching for file changes with StatReloader
INFO 2024-02-16 22:04:53,743 "GET /random/dice HTTP/1.1" 301 0
INFO 2024-02-16 22:04:53,747 Была вызвана функция dice
INFO 2024-02-16 22:04:53,749 "GET /random/dice/ HTTP/1.1" 200 44
INFO 2024-02-16 22:08:37,555 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 22:08:38,587 Watching for file changes with StatReloader
INFO 2024-02-16 22:08:40,067 Была вызвана функция dice
INFO 2024-02-16 22:08:40,076 "GET /random/dice/ HTTP/1.1" 200 44
WARNING 2024-02-16 22:08:43,032 Not Found: /random/dice/4
WARNING 2024-02-16 22:08:43,033 "GET /random/dice/4 HTTP/1.1" 404 3385
INFO 2024-02-16 22:09:10,652 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-16 22:09:11,809 Watching for file changes with StatReloader
INFO 2024-02-16 22:10:08,161 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-16 22:10:09,274 Watching for file changes with StatReloader
ERROR 2024-02-16 22:10:20,160 Internal Server Error: /random/dice/4
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 17, in wrapper
    result = func(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 62, in dice
    result.append({'Попытка': i + 1, 'результат': result})
AttributeError: 'int' object has no attribute 'append'
ERROR 2024-02-16 22:10:20,161 "GET /random/dice/4 HTTP/1.1" 500 63754
WARNING 2024-02-16 22:10:28,888 Not Found: /random/dice/
WARNING 2024-02-16 22:10:28,889 "GET /random/dice/ HTTP/1.1" 404 3395
INFO 2024-02-16 22:10:40,244 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 22:10:41,569 Watching for file changes with StatReloader
WARNING 2024-02-16 22:10:42,753 Not Found: /random/dice/
WARNING 2024-02-16 22:10:42,753 "GET /random/dice/ HTTP/1.1" 404 3395
INFO 2024-02-16 22:11:17,608 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 22:11:18,854 Watching for file changes with StatReloader
WARNING 2024-02-16 22:11:21,717 Not Found: /random/dice/
WARNING 2024-02-16 22:11:21,718 "GET /random/dice/ HTTP/1.1" 404 3395
INFO 2024-02-16 22:11:31,443 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 22:11:32,816 Watching for file changes with StatReloader
WARNING 2024-02-16 22:11:36,066 Not Found: /random/dice/
WARNING 2024-02-16 22:11:36,068 "GET /random/dice/ HTTP/1.1" 404 3395
INFO 2024-02-16 22:12:05,805 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-16 22:12:06,528 Watching for file changes with StatReloader
INFO 2024-02-16 22:12:07,721 Была вызвана функция dice
INFO 2024-02-16 22:12:07,722 "GET /random/dice/ HTTP/1.1" 200 44
INFO 2024-02-16 22:12:13,851 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-16 22:12:14,661 Watching for file changes with StatReloader
INFO 2024-02-16 22:12:38,088 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-16 22:12:39,796 Watching for file changes with StatReloader
INFO 2024-02-16 22:13:31,941 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 22:13:33,299 Watching for file changes with StatReloader
ERROR 2024-02-16 22:13:37,680 Internal Server Error: /random/dice_pd/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 17, in wrapper
    result = func(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 69, in dice_pd
    for i in range(n):
TypeError: 'NoneType' object cannot be interpreted as an integer
ERROR 2024-02-16 22:13:37,682 "GET /random/dice_pd/ HTTP/1.1" 500 63361
WARNING 2024-02-16 22:13:41,163 Not Found: /random/dice_pd/10
WARNING 2024-02-16 22:13:41,164 "GET /random/dice_pd/10 HTTP/1.1" 404 3575
WARNING 2024-02-16 22:14:03,502 Not Found: /random/dice_pd/10
WARNING 2024-02-16 22:14:03,503 "GET /random/dice_pd/10 HTTP/1.1" 404 3575
INFO 2024-02-16 22:14:03,547 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-16 22:14:04,322 Watching for file changes with StatReloader
ERROR 2024-02-16 22:14:05,674 Internal Server Error: /random/dice_pd/10
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 17, in wrapper
    result = func(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 71, in dice_pd
    result.append({'Попытка': i + 1, 'результат': result})
AttributeError: 'int' object has no attribute 'append'
INFO 2024-02-16 22:14:05,678 - Broken pipe from ('127.0.0.1', 55772)
ERROR 2024-02-16 22:14:06,848 Internal Server Error: /random/dice_pd/10
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 17, in wrapper
    result = func(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 71, in dice_pd
    result.append({'Попытка': i + 1, 'результат': result})
AttributeError: 'int' object has no attribute 'append'
ERROR 2024-02-16 22:14:06,922 "GET /random/dice_pd/10 HTTP/1.1" 500 63692
ERROR 2024-02-16 22:14:07,497 Internal Server Error: /random/dice_pd/10
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 17, in wrapper
    result = func(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 71, in dice_pd
    result.append({'Попытка': i + 1, 'результат': result})
AttributeError: 'int' object has no attribute 'append'
ERROR 2024-02-16 22:14:07,498 "GET /random/dice_pd/10 HTTP/1.1" 500 63692
INFO 2024-02-16 22:14:37,796 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-16 22:14:38,840 Watching for file changes with StatReloader
INFO 2024-02-16 22:14:40,139 Была вызвана функция dice_pd
INFO 2024-02-16 22:14:40,140 "GET /random/dice_pd/10 HTTP/1.1" 200 1041
INFO 2024-02-16 22:29:04,000 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-16 22:29:05,396 Watching for file changes with StatReloader
WARNING 2024-02-16 22:54:01,587 Not Found: /random/posts/
WARNING 2024-02-16 22:54:01,589 "GET /random/posts/ HTTP/1.1" 404 3576
WARNING 2024-02-16 22:54:04,065 Not Found: /random/posts/1
WARNING 2024-02-16 22:54:04,066 "GET /random/posts/1 HTTP/1.1" 404 3579
WARNING 2024-02-16 22:54:07,421 Not Found: /random/posts/2
WARNING 2024-02-16 22:54:07,422 "GET /random/posts/2 HTTP/1.1" 404 3579
WARNING 2024-02-16 22:54:14,474 Not Found: /posts/2
WARNING 2024-02-16 22:54:14,476 "GET /posts/2 HTTP/1.1" 404 2375
WARNING 2024-02-16 22:54:17,380 Not Found: /posts/3
WARNING 2024-02-16 22:54:17,383 "GET /posts/3 HTTP/1.1" 404 2375
INFO 2024-02-16 22:55:27,347 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/django_seminars/urls.py changed, reloading.
INFO 2024-02-16 22:55:28,764 Watching for file changes with StatReloader
INFO 2024-02-16 22:55:57,675 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 22:55:58,763 Watching for file changes with StatReloader
INFO 2024-02-16 22:57:53,176 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-16 22:57:54,346 Watching for file changes with StatReloader
INFO 2024-02-16 23:01:02,248 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-16 23:01:03,042 Watching for file changes with StatReloader
INFO 2024-02-16 23:01:15,347 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-16 23:01:15,945 Watching for file changes with StatReloader
WARNING 2024-02-16 23:01:19,345 Not Found: /posts/post/3
WARNING 2024-02-16 23:01:19,346 "GET /posts/post/3 HTTP/1.1" 404 2586
WARNING 2024-02-16 23:01:24,194 Not Found: /posts//3
WARNING 2024-02-16 23:01:24,195 "GET /posts//3 HTTP/1.1" 404 2574
WARNING 2024-02-16 23:01:27,944 Not Found: /posts/3
WARNING 2024-02-16 23:01:27,944 "GET /posts/3 HTTP/1.1" 404 2571
WARNING 2024-02-16 23:01:52,923 Not Found: /posts/post/3
WARNING 2024-02-16 23:01:52,923 "GET /posts/post/3 HTTP/1.1" 404 2586
INFO 2024-02-16 23:05:14,139 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-16 23:05:15,145 Watching for file changes with StatReloader
INFO 2024-02-16 23:05:17,913 "GET /posts/post/3 HTTP/1.1" 301 0
ERROR 2024-02-16 23:05:18,035 Internal Server Error: /posts/post/3/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: get_posts() got an unexpected keyword argument 'post_id'
ERROR 2024-02-16 23:05:18,035 "GET /posts/post/3/ HTTP/1.1" 500 56111
INFO 2024-02-16 23:06:44,017 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:06:45,040 Watching for file changes with StatReloader
INFO 2024-02-16 23:07:38,189 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-16 23:07:39,073 Watching for file changes with StatReloader
INFO 2024-02-16 23:08:43,745 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-16 23:08:45,439 Watching for file changes with StatReloader
INFO 2024-02-16 23:08:51,078 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-16 23:08:51,796 Watching for file changes with StatReloader
ERROR 2024-02-16 23:08:55,034 Internal Server Error: /posts/post/3/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view blog.views.author_post didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 23:08:55,035 "GET /posts/post/3/ HTTP/1.1" 500 60607
INFO 2024-02-16 23:11:08,437 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:11:09,293 Watching for file changes with StatReloader
WARNING 2024-02-16 23:11:12,014 Not Found: /posts/post/3/
WARNING 2024-02-16 23:11:12,014 "GET /posts/post/3/ HTTP/1.1" 404 2586
INFO 2024-02-16 23:11:34,025 "GET /posts/3 HTTP/1.1" 301 0
INFO 2024-02-16 23:11:34,047 "GET /posts/3/ HTTP/1.1" 200 313
INFO 2024-02-16 23:11:39,321 "GET /posts/2/ HTTP/1.1" 200 189
INFO 2024-02-16 23:11:42,461 "GET /posts/1 HTTP/1.1" 301 0
INFO 2024-02-16 23:11:42,469 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-16 23:12:29,611 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:12:30,376 Watching for file changes with StatReloader
INFO 2024-02-16 23:12:33,384 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-16 23:12:34,232 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-16 23:12:34,885 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-16 23:13:21,586 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:13:22,610 Watching for file changes with StatReloader
INFO 2024-02-16 23:13:25,948 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:13:27,337 Watching for file changes with StatReloader
INFO 2024-02-16 23:14:49,791 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:14:50,787 Watching for file changes with StatReloader
INFO 2024-02-16 23:16:19,523 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:16:20,370 Watching for file changes with StatReloader
INFO 2024-02-16 23:16:24,001 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-16 23:16:28,878 "GET /posts/post/1 HTTP/1.1" 301 0
ERROR 2024-02-16 23:16:29,010 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: author_post() got an unexpected keyword argument 'post_id'
ERROR 2024-02-16 23:16:29,011 "GET /posts/post/1/ HTTP/1.1" 500 55988
INFO 2024-02-16 23:17:41,614 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:17:42,365 Watching for file changes with StatReloader
ERROR 2024-02-16 23:17:45,283 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: author_post() got an unexpected keyword argument 'post_id'
ERROR 2024-02-16 23:17:45,284 "GET /posts/post/1/ HTTP/1.1" 500 56125
ERROR 2024-02-16 23:17:46,348 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: author_post() got an unexpected keyword argument 'post_id'
ERROR 2024-02-16 23:17:46,349 "GET /posts/post/1/ HTTP/1.1" 500 56125
ERROR 2024-02-16 23:17:47,033 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: author_post() got an unexpected keyword argument 'post_id'
ERROR 2024-02-16 23:17:47,034 "GET /posts/post/1/ HTTP/1.1" 500 56125
ERROR 2024-02-16 23:17:48,249 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: author_post() got an unexpected keyword argument 'post_id'
ERROR 2024-02-16 23:17:48,250 "GET /posts/post/1/ HTTP/1.1" 500 56125
INFO 2024-02-16 23:17:56,885 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:17:57,999 Watching for file changes with StatReloader
ERROR 2024-02-16 23:17:59,367 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view blog.views.author_post didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 23:17:59,368 "GET /posts/post/1/ HTTP/1.1" 500 60607
INFO 2024-02-16 23:20:37,262 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:20:38,323 Watching for file changes with StatReloader
INFO 2024-02-16 23:23:20,448 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-16 23:23:21,572 Watching for file changes with StatReloader
ERROR 2024-02-16 23:23:24,083 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view blog.views.author_post didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 23:23:24,084 "GET /posts/post/1/ HTTP/1.1" 500 60601
ERROR 2024-02-16 23:23:24,881 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view blog.views.author_post didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 23:23:24,883 "GET /posts/post/1/ HTTP/1.1" 500 60601
INFO 2024-02-16 23:23:54,760 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:23:55,531 Watching for file changes with StatReloader
ERROR 2024-02-16 23:23:58,373 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: author_post() got multiple values for argument 'n'
ERROR 2024-02-16 23:23:58,373 "GET /posts/post/1/ HTTP/1.1" 500 56087
INFO 2024-02-16 23:24:22,403 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:24:23,141 Watching for file changes with StatReloader
INFO 2024-02-16 23:26:25,549 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-16 23:26:26,887 Watching for file changes with StatReloader
ERROR 2024-02-16 23:26:34,313 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view blog.views.author_post didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 23:26:34,314 "GET /posts/post/1/ HTTP/1.1" 500 60607
INFO 2024-02-16 23:27:36,915 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-16 23:27:38,218 Watching for file changes with StatReloader
ERROR 2024-02-16 23:27:44,219 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view blog.views.author_post didn't return an HttpResponse object. It returned None instead.
ERROR 2024-02-16 23:27:44,219 "GET /posts/post/1/ HTTP/1.1" 500 60607
INFO 2024-02-16 23:28:26,927 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-16 23:28:27,997 Watching for file changes with StatReloader
INFO 2024-02-16 23:28:30,435 "GET /posts/post/1/ HTTP/1.1" 200 0
INFO 2024-02-16 23:28:42,621 "GET /posts/post/2 HTTP/1.1" 301 0
INFO 2024-02-16 23:28:42,626 "GET /posts/post/2/ HTTP/1.1" 200 0
INFO 2024-02-16 23:28:45,022 "GET /posts/post/4 HTTP/1.1" 301 0
INFO 2024-02-16 23:28:45,030 "GET /posts/post/4/ HTTP/1.1" 200 0
INFO 2024-02-16 23:28:53,508 "GET /posts/4 HTTP/1.1" 301 0
INFO 2024-02-16 23:28:53,529 "GET /posts/4/ HTTP/1.1" 200 189
INFO 2024-02-16 23:28:56,959 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-16 23:30:20,488 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-16 23:30:21,784 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-16 23:31:01,029 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-16 23:31:02,341 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-16 23:31:03,274 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-17 08:04:31,193 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-17 08:04:32,441 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-17 08:04:33,129 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-17 08:05:07,651 Watching for file changes with StatReloader
INFO 2024-02-17 08:05:13,576 "GET /posts/1/ HTTP/1.1" 200 553
INFO 2024-02-17 08:05:14,115 "GET /posts/1/ HTTP/1.1" 200 553
WARNING 2024-02-17 08:05:19,799 Not Found: /post
WARNING 2024-02-17 08:05:19,800 "GET /post HTTP/1.1" 404 2757
INFO 2024-02-17 08:05:24,649 "GET /posts/1/ HTTP/1.1" 200 553
WARNING 2024-02-17 08:05:27,159 Not Found: /posts/
WARNING 2024-02-17 08:05:27,159 "GET /posts/ HTTP/1.1" 404 2763
INFO 2024-02-17 08:05:59,090 "GET /posts/post/1/ HTTP/1.1" 200 0
INFO 2024-02-17 08:06:03,729 "GET /posts/post/2/ HTTP/1.1" 200 0
INFO 2024-02-17 08:06:06,445 "GET /posts/post/3/ HTTP/1.1" 200 0
INFO 2024-02-17 08:07:51,308 "GET /posts/post/3/ HTTP/1.1" 200 0
INFO 2024-02-17 08:07:53,178 "GET /posts/post/3/ HTTP/1.1" 200 0
WARNING 2024-02-17 08:07:55,558 Not Found: /posts/posts
WARNING 2024-02-17 08:07:55,559 "GET /posts/posts HTTP/1.1" 404 2778
WARNING 2024-02-17 08:07:58,372 Not Found: /posts/posts/3
WARNING 2024-02-17 08:07:58,373 "GET /posts/posts/3 HTTP/1.1" 404 2784
INFO 2024-02-17 08:08:04,394 "GET /posts/3/ HTTP/1.1" 200 358
INFO 2024-02-17 08:08:07,864 "GET /posts/2/ HTTP/1.1" 200 189
INFO 2024-02-17 08:08:09,793 "GET /posts/1/ HTTP/1.1" 200 680
INFO 2024-02-17 08:40:44,619 Watching for file changes with StatReloader
ERROR 2024-02-17 08:40:53,346 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 12, in author_post
    post = Post.object.filter(post_id=post_id)
AttributeError: type object 'Post' has no attribute 'object'
ERROR 2024-02-17 08:40:53,347 "GET /posts/post/1/ HTTP/1.1" 500 58910
INFO 2024-02-17 08:41:25,970 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-17 08:41:26,635 Watching for file changes with StatReloader
ERROR 2024-02-17 08:41:29,599 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 12, in author_post
    post = Post.objects.filter(post_id=post_id)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'post_id' into field. Choices are: author, author_id, category, comment, content, id, is_public, pub_date, title, views_count
ERROR 2024-02-17 08:41:29,605 "GET /posts/post/1/ HTTP/1.1" 500 104013
ERROR 2024-02-17 08:42:58,531 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 12, in author_post
    post = Post.objects.filter(post_id=post_id)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'post_id' into field. Choices are: author, author_id, category, comment, content, id, is_public, pub_date, title, views_count
ERROR 2024-02-17 08:42:58,533 "GET /posts/post/1/ HTTP/1.1" 500 104013
ERROR 2024-02-17 08:42:59,602 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 12, in author_post
    post = Post.objects.filter(post_id=post_id)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'post_id' into field. Choices are: author, author_id, category, comment, content, id, is_public, pub_date, title, views_count
ERROR 2024-02-17 08:42:59,607 "GET /posts/post/1/ HTTP/1.1" 500 104013
ERROR 2024-02-17 08:43:00,619 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 12, in author_post
    post = Post.objects.filter(post_id=post_id)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'post_id' into field. Choices are: author, author_id, category, comment, content, id, is_public, pub_date, title, views_count
ERROR 2024-02-17 08:43:00,625 "GET /posts/post/1/ HTTP/1.1" 500 104013
INFO 2024-02-17 08:47:17,023 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-17 08:47:18,289 Watching for file changes with StatReloader
ERROR 2024-02-17 08:47:20,413 Internal Server Error: /posts/post/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 12, in author_post
    post = Post.objects.get(post_id=post_id)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'post_id' into field. Choices are: author, author_id, category, comment, content, id, is_public, pub_date, title, views_count
ERROR 2024-02-17 08:47:20,476 "GET /posts/post/1/ HTTP/1.1" 500 108621
INFO 2024-02-17 08:48:03,903 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-17 08:48:05,000 Watching for file changes with StatReloader
INFO 2024-02-17 08:48:07,253 "GET /posts/post/1/ HTTP/1.1" 200 2626
INFO 2024-02-17 08:48:19,041 "GET /posts/post/2/ HTTP/1.1" 200 3011
INFO 2024-02-17 08:49:47,303 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-17 08:49:49,281 Watching for file changes with StatReloader
INFO 2024-02-17 08:50:49,820 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-17 08:50:50,515 Watching for file changes with StatReloader
INFO 2024-02-17 08:51:17,359 "GET /posts/post/2/ HTTP/1.1" 200 3011
INFO 2024-02-17 08:51:19,173 "GET /posts/post/2/ HTTP/1.1" 200 3011
INFO 2024-02-17 08:51:20,376 "GET /posts/post/2/ HTTP/1.1" 200 3011
ERROR 2024-02-17 08:51:31,519 Internal Server Error: /posts/post/2/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 15, in author_post
    post.save()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1036, in _save_table
    updated = self._do_update(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1101, in _do_update
    return filtered._update(values) > 0
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: database is locked
ERROR 2024-02-17 08:51:31,526 "GET /posts/post/2/ HTTP/1.1" 500 180794
INFO 2024-02-17 08:51:36,512 "GET /posts/post/2/ HTTP/1.1" 200 3011
INFO 2024-02-17 08:51:38,051 "GET /posts/post/2/ HTTP/1.1" 200 3011
INFO 2024-02-17 08:59:28,919 Watching for file changes with StatReloader
WARNING 2024-02-17 08:59:31,613 Not Found: /posts/
WARNING 2024-02-17 08:59:31,614 "GET /posts/ HTTP/1.1" 404 2763
INFO 2024-02-17 08:59:35,068 "GET /posts/1/ HTTP/1.1" 200 680
INFO 2024-02-17 09:00:56,255 "GET /posts/1/ HTTP/1.1" 200 680
INFO 2024-02-17 09:01:58,534 "GET /posts/1/ HTTP/1.1" 200 654
INFO 2024-02-17 09:02:05,925 "GET /posts/post/2/ HTTP/1.1" 200 3011
INFO 2024-02-17 09:04:06,447 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-17 09:04:07,614 Watching for file changes with StatReloader
INFO 2024-02-17 09:07:13,619 "GET /posts/1/ HTTP/1.1" 200 654
INFO 2024-02-17 09:07:14,338 "GET /posts/1/ HTTP/1.1" 200 654
ERROR 2024-02-17 09:07:20,693 Internal Server Error: /posts/post/2/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 15, in author_post
    post.save()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1036, in _save_table
    updated = self._do_update(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1101, in _do_update
    return filtered._update(values) > 0
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: database is locked
INFO 2024-02-17 09:07:20,768 - Broken pipe from ('127.0.0.1', 58223)
ERROR 2024-02-17 09:07:25,787 Internal Server Error: /posts/post/2/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 15, in author_post
    post.save()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1036, in _save_table
    updated = self._do_update(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1101, in _do_update
    return filtered._update(values) > 0
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: database is locked
INFO 2024-02-17 09:07:25,804 - Broken pipe from ('127.0.0.1', 58224)
ERROR 2024-02-17 09:07:36,293 Internal Server Error: /posts/post/2/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 15, in author_post
    post.save()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1036, in _save_table
    updated = self._do_update(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1101, in _do_update
    return filtered._update(values) > 0
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: database is locked
INFO 2024-02-17 09:07:36,346 - Broken pipe from ('127.0.0.1', 58225)
ERROR 2024-02-17 09:07:36,505 Internal Server Error: /posts/1/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 8, in get_posts
    return render(request, 'blog/posts.html', {'posts': posts})
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 198, in render
    len_values = len(values)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: database is locked
INFO 2024-02-17 09:07:36,522 - Broken pipe from ('127.0.0.1', 58228)
ERROR 2024-02-17 09:07:36,506 Internal Server Error: /posts/post/2/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 15, in author_post
    post.save()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1036, in _save_table
    updated = self._do_update(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1101, in _do_update
    return filtered._update(values) > 0
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: database is locked
ERROR 2024-02-17 09:07:36,591 "GET /posts/post/2/ HTTP/1.1" 500 181121
ERROR 2024-02-17 09:08:00,677 Internal Server Error: /posts/post/2/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 17, in author_post
    return render(request, 'blog/post.html', {'post':post, 'comments': comments})
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 515, in parse
    self.unclosed_block_tag(parse_until)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/base.py", line 578, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 11: 'for'. Looking for one of: empty, endfor.
ERROR 2024-02-17 09:08:00,690 "GET /posts/post/2/ HTTP/1.1" 500 137135
INFO 2024-02-17 09:08:54,881 "GET /posts/post/2/ HTTP/1.1" 200 16981
INFO 2024-02-17 09:12:14,347 "GET /posts/post/2/ HTTP/1.1" 200 19442
INFO 2024-02-17 09:14:21,397 "GET /posts/post/2/ HTTP/1.1" 200 19220
INFO 2024-02-17 09:14:21,681 "GET /posts/post/2/ HTTP/1.1" 200 19220
INFO 2024-02-17 09:14:22,219 "GET /posts/post/2/ HTTP/1.1" 200 19220
INFO 2024-02-17 09:14:33,663 "GET /posts/post/2/ HTTP/1.1" 200 19376
INFO 2024-02-17 09:15:14,300 "GET /posts/post/2/ HTTP/1.1" 200 19532
INFO 2024-02-17 09:17:29,950 "GET /posts/post/2/ HTTP/1.1" 200 19792
INFO 2024-02-17 09:17:31,380 "GET /posts/post/2/ HTTP/1.1" 200 19792
INFO 2024-02-17 09:18:15,004 "GET /posts/post/2/ HTTP/1.1" 200 19720
INFO 2024-02-17 09:18:17,208 "GET /posts/post/2/ HTTP/1.1" 200 19720
INFO 2024-02-18 15:13:46,381 Watching for file changes with StatReloader
INFO 2024-02-18 15:14:06,060 "GET /posts/post/2/ HTTP/1.1" 200 19720
INFO 2024-02-18 15:50:37,444 Watching for file changes with StatReloader
INFO 2024-02-18 15:50:59,101 "GET /posts/1/ HTTP/1.1" 200 654
INFO 2024-02-19 19:29:33,937 Watching for file changes with StatReloader
WARNING 2024-02-19 19:29:43,511 Not Found: /games/random_games
WARNING 2024-02-19 19:29:43,511 "GET /games/random_games HTTP/1.1" 404 2799
ERROR 2024-02-19 19:29:51,589 Internal Server Error: /random/games/random_games
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 96, in random_games
    return render(request, 'myapp4/random_games.html', {'form': form})
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/random_games.html
ERROR 2024-02-19 19:29:51,592 "GET /random/games/random_games HTTP/1.1" 500 74157
INFO 2024-02-19 19:30:24,371 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-19 19:30:25,686 Watching for file changes with StatReloader
INFO 2024-02-19 19:30:27,083 "GET /random/games/random_games HTTP/1.1" 301 0
ERROR 2024-02-19 19:30:27,141 Internal Server Error: /random/games/random_games/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 96, in random_games
    return render(request, 'myapp4/random_games.html', {'form': form})
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/random_games.html
ERROR 2024-02-19 19:30:27,144 "GET /random/games/random_games/ HTTP/1.1" 500 74169
ERROR 2024-02-19 19:31:55,743 Internal Server Error: /random/games/random_games/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 96, in random_games
    return render(request, 'myapp4/random_games.html', {'form': form})
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/random_games.html
ERROR 2024-02-19 19:31:55,744 "GET /random/games/random_games/ HTTP/1.1" 500 74169
WARNING 2024-02-19 19:31:59,644 Not Found: /random/
WARNING 2024-02-19 19:31:59,644 "GET /random/ HTTP/1.1" 404 4140
ERROR 2024-02-19 19:32:10,108 Internal Server Error: /random/games/random_games/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 96, in random_games
    return render(request, 'myapp4/random_games.html', {'form': form})
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/random_games.html
ERROR 2024-02-19 19:32:10,109 "GET /random/games/random_games/ HTTP/1.1" 500 74169
INFO 2024-02-19 19:33:09,717 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/urls.py changed, reloading.
INFO 2024-02-19 19:33:10,709 Watching for file changes with StatReloader
ERROR 2024-02-19 19:33:11,869 Internal Server Error: /random/games/random_games/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 96, in random_games
    return render(request, 'myapp4/random_games.html', {'form': form})
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/random_games.html
ERROR 2024-02-19 19:33:11,871 "GET /random/games/random_games/ HTTP/1.1" 500 74169
INFO 2024-02-19 19:33:46,397 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:33:48,167 Watching for file changes with StatReloader
INFO 2024-02-19 19:33:48,993 "GET /random/games/random_games/ HTTP/1.1" 200 957
INFO 2024-02-19 19:33:57,607 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:34:09,980 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:36:48,706 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:37:13,745 "POST /random/games/random_games/ HTTP/1.1" 200 986
INFO 2024-02-19 19:37:40,534 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:38:25,586 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/forms.py changed, reloading.
INFO 2024-02-19 19:38:26,459 Watching for file changes with StatReloader
INFO 2024-02-19 19:38:30,098 "POST /random/games/random_games/ HTTP/1.1" 200 1087
INFO 2024-02-19 19:38:38,277 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:38:39,976 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:39:25,256 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:39:26,691 Watching for file changes with StatReloader
INFO 2024-02-19 19:39:33,530 "GET /random/games/random_games/ HTTP/1.1" 200 957
INFO 2024-02-19 19:39:37,864 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:39:40,065 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:39:42,102 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:39:44,693 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:39:47,345 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:40:14,143 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:40:15,284 Watching for file changes with StatReloader
INFO 2024-02-19 19:40:16,740 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:44:16,589 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:44:17,818 Watching for file changes with StatReloader
INFO 2024-02-19 19:44:21,783 Watching for file changes with StatReloader
INFO 2024-02-19 19:44:32,850 "POST /random/games/random_games/ HTTP/1.1" 200 1087
INFO 2024-02-19 19:46:05,314 Watching for file changes with StatReloader
INFO 2024-02-19 19:46:11,001 "GET /random/games/random_games/ HTTP/1.1" 200 957
INFO 2024-02-19 19:46:15,508 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:46:36,310 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:46:37,269 Watching for file changes with StatReloader
INFO 2024-02-19 19:46:41,769 "GET /random/games/random_games/ HTTP/1.1" 200 957
INFO 2024-02-19 19:46:44,075 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:47:06,031 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:47:06,912 Watching for file changes with StatReloader
INFO 2024-02-19 19:47:08,466 "POST /random/games/random_games/ HTTP/1.1" 200 976
INFO 2024-02-19 19:47:31,825 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:47:32,730 Watching for file changes with StatReloader
INFO 2024-02-19 19:47:35,599 Была вызвана функция coin
INFO 2024-02-19 19:47:35,600 "POST /random/games/random_games/ HTTP/1.1" 200 151
INFO 2024-02-19 19:47:40,409 Была вызвана функция coin
INFO 2024-02-19 19:47:40,410 "POST /random/games/random_games/ HTTP/1.1" 200 203
INFO 2024-02-19 19:49:33,923 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/forms.py changed, reloading.
INFO 2024-02-19 19:49:35,018 Watching for file changes with StatReloader
INFO 2024-02-19 19:49:41,094 Была вызвана функция coin
INFO 2024-02-19 19:49:41,094 "POST /random/games/random_games/ HTTP/1.1" 200 155
INFO 2024-02-19 19:49:46,272 "GET /random/games/random_games/ HTTP/1.1" 200 1014
INFO 2024-02-19 19:49:51,382 Была вызвана функция coin
INFO 2024-02-19 19:49:51,384 "POST /random/games/random_games/ HTTP/1.1" 200 139
INFO 2024-02-19 19:50:13,114 "GET /random/games/random_games/ HTTP/1.1" 200 916
INFO 2024-02-19 19:50:20,247 "GET /random/games/random_games/ HTTP/1.1" 200 927
INFO 2024-02-19 19:51:28,784 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:51:30,356 Watching for file changes with StatReloader
INFO 2024-02-19 19:52:12,664 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:52:14,237 Watching for file changes with StatReloader
INFO 2024-02-19 19:53:31,833 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:53:33,465 Watching for file changes with StatReloader
INFO 2024-02-19 19:54:19,336 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:54:20,119 Watching for file changes with StatReloader
INFO 2024-02-19 19:54:23,822 "GET /random/games/random_games/ HTTP/1.1" 200 927
INFO 2024-02-19 19:54:27,642 Была вызвана функция coin
INFO 2024-02-19 19:54:27,643 "POST /random/games/random_games/ HTTP/1.1" 200 153
INFO 2024-02-19 19:54:34,427 Была вызвана функция dice
INFO 2024-02-19 19:54:34,428 "POST /random/games/random_games/ HTTP/1.1" 200 44
INFO 2024-02-19 19:56:07,873 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:56:08,806 Watching for file changes with StatReloader
ERROR 2024-02-19 19:56:15,086 Internal Server Error: /random/games/random_games/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 95, in random_games
    return dice(request, count)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 18, in wrapper
    result = func(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py", line 62, in dice
    result.append({'Попытка': i + 1, 'результат': result})
AttributeError: 'int' object has no attribute 'append'
ERROR 2024-02-19 19:56:15,088 "POST /random/games/random_games/ HTTP/1.1" 500 68570
INFO 2024-02-19 19:57:08,512 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/views.py changed, reloading.
INFO 2024-02-19 19:57:09,536 Watching for file changes with StatReloader
INFO 2024-02-19 19:57:16,198 Была вызвана функция dice
INFO 2024-02-19 19:57:16,199 "POST /random/games/random_games/ HTTP/1.1" 200 480
INFO 2024-02-19 19:57:26,405 Была вызвана функция dice
INFO 2024-02-19 19:57:26,405 "POST /random/games/random_games/ HTTP/1.1" 200 1041
INFO 2024-02-19 19:57:48,013 Была вызвана функция random_num
INFO 2024-02-19 19:57:48,014 "POST /random/games/random_games/ HTTP/1.1" 200 52
INFO 2024-02-19 20:15:27,399 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/models.py changed, reloading.
INFO 2024-02-19 20:15:28,573 Watching for file changes with StatReloader
INFO 2024-02-19 20:16:34,671 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/models.py changed, reloading.
INFO 2024-02-19 20:16:36,083 Watching for file changes with StatReloader
INFO 2024-02-19 20:20:19,096 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:20:20,599 Watching for file changes with StatReloader
INFO 2024-02-19 20:21:07,713 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:21:08,581 Watching for file changes with StatReloader
INFO 2024-02-19 20:21:31,229 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:21:32,096 Watching for file changes with StatReloader
INFO 2024-02-19 20:21:36,049 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:21:37,027 Watching for file changes with StatReloader
INFO 2024-02-19 20:22:37,695 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:22:39,015 Watching for file changes with StatReloader
INFO 2024-02-19 20:24:10,122 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:24:11,448 Watching for file changes with StatReloader
INFO 2024-02-19 20:24:25,031 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:24:26,227 Watching for file changes with StatReloader
INFO 2024-02-19 20:24:45,310 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:24:46,274 Watching for file changes with StatReloader
INFO 2024-02-19 20:25:50,438 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:25:51,369 Watching for file changes with StatReloader
INFO 2024-02-19 20:27:02,520 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:27:03,732 Watching for file changes with StatReloader
INFO 2024-02-19 20:30:19,436 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-19 20:30:20,652 Watching for file changes with StatReloader
INFO 2024-02-19 20:30:26,489 "GET /author/author_form HTTP/1.1" 301 0
ERROR 2024-02-19 20:30:26,623 Internal Server Error: /author/author_form/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: author_post() missing 1 required positional argument: 'post_id'
ERROR 2024-02-19 20:30:26,624 "GET /author/author_form/ HTTP/1.1" 500 55869
INFO 2024-02-19 20:32:51,156 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-19 20:32:52,534 Watching for file changes with StatReloader
INFO 2024-02-19 20:32:57,220 "GET /author/author_form/ HTTP/1.1" 200 387
INFO 2024-02-19 20:33:44,691 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:33:45,478 Watching for file changes with StatReloader
INFO 2024-02-19 20:33:46,548 "GET /author/author_form/ HTTP/1.1" 200 387
INFO 2024-02-19 20:38:33,139 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-19 20:38:34,028 Watching for file changes with StatReloader
INFO 2024-02-19 20:38:37,131 "GET /author/author_form/ HTTP/1.1" 200 387
INFO 2024-02-19 20:38:44,511 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-19 20:38:45,261 Watching for file changes with StatReloader
INFO 2024-02-19 20:38:50,551 Watching for file changes with StatReloader
INFO 2024-02-19 20:38:53,829 "GET /author/author_form/ HTTP/1.1" 200 387
INFO 2024-02-19 20:38:54,636 "GET /author/author_form/ HTTP/1.1" 200 387
ERROR 2024-02-19 20:38:55,963 Internal Server Error: /author/author_form/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 25, in author_form
    form.save()
AttributeError: 'AuthorForm' object has no attribute 'save'
ERROR 2024-02-19 20:38:55,964 "POST /author/author_form/ HTTP/1.1" 500 59941
INFO 2024-02-19 20:39:08,363 "GET /author/author_form/ HTTP/1.1" 200 387
WARNING 2024-02-19 20:39:08,723 Not Found: /favicon.ico
WARNING 2024-02-19 20:39:08,724 "GET /favicon.ico HTTP/1.1" 404 2964
INFO 2024-02-19 20:40:11,032 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/models.py changed, reloading.
INFO 2024-02-19 20:40:13,154 Watching for file changes with StatReloader
INFO 2024-02-19 20:40:14,177 "GET /author/author_form/ HTTP/1.1" 200 387
INFO 2024-02-19 20:41:15,739 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-19 20:41:17,355 Watching for file changes with StatReloader
INFO 2024-02-19 20:41:18,664 "GET /author/author_form/ HTTP/1.1" 200 387
INFO 2024-02-19 20:41:19,612 "GET /author/author_form/ HTTP/1.1" 200 387
INFO 2024-02-19 20:41:24,614 "GET /author/author_form/ HTTP/1.1" 200 387
ERROR 2024-02-19 20:41:27,915 Internal Server Error: /author/author_form/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 25, in author_form
    form.save()
AttributeError: 'AuthorForm' object has no attribute 'save'
ERROR 2024-02-19 20:41:27,915 "POST /author/author_form/ HTTP/1.1" 500 60074
INFO 2024-02-19 20:41:58,017 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-19 20:41:59,351 Watching for file changes with StatReloader
INFO 2024-02-19 20:42:02,025 "GET /author/author_form/ HTTP/1.1" 200 387
INFO 2024-02-19 20:42:03,641 "POST /author/author_form/ HTTP/1.1" 302 0
INFO 2024-02-19 20:42:03,657 "GET /author/author_form/ HTTP/1.1" 200 387
INFO 2024-02-19 20:42:04,528 "POST /author/author_form/ HTTP/1.1" 302 0
INFO 2024-02-19 20:42:04,540 "GET /author/author_form/ HTTP/1.1" 200 387
INFO 2024-02-19 20:43:31,171 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-19 20:43:32,880 Watching for file changes with StatReloader
INFO 2024-02-19 20:44:18,835 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-19 20:44:19,616 Watching for file changes with StatReloader
INFO 2024-02-19 20:44:23,011 "GET /author/author_form/ HTTP/1.1" 200 1152
INFO 2024-02-19 20:46:44,403 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/models.py changed, reloading.
INFO 2024-02-19 20:46:45,392 Watching for file changes with StatReloader
INFO 2024-02-19 20:46:54,630 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/models.py changed, reloading.
INFO 2024-02-19 20:46:55,702 Watching for file changes with StatReloader
INFO 2024-02-19 20:47:39,978 "POST /author/author_form/ HTTP/1.1" 200 1339
INFO 2024-02-19 20:47:52,680 "POST /author/author_form/ HTTP/1.1" 200 1339
ERROR 2024-02-19 20:49:08,949 Internal Server Error: /author/author_form/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 25, in author_form
    form.save()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/forms/models.py", line 552, in save
    self.instance.save()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/models.py", line 14, in save
    super().save(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1835, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/backends/base/operations.py", line 216, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/utils.py", line 97, in inner
    with self:
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
django.db.utils.OperationalError: database is locked
ERROR 2024-02-19 20:49:09,765 "POST /author/author_form/ HTTP/1.1" 500 126562
INFO 2024-02-19 20:49:24,373 "POST /author/author_form/ HTTP/1.1" 302 0
INFO 2024-02-19 20:49:24,405 "GET /author/author_form/ HTTP/1.1" 200 1152
INFO 2024-02-19 20:55:22,284 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-19 20:55:23,259 Watching for file changes with StatReloader
INFO 2024-02-19 20:56:24,461 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-19 20:56:25,198 Watching for file changes with StatReloader
INFO 2024-02-19 20:56:28,884 "GET /author/author_form/ HTTP/1.1" 200 1188
INFO 2024-02-19 20:57:23,870 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-19 20:57:24,661 Watching for file changes with StatReloader
INFO 2024-02-20 11:18:26,660 "GET / HTTP/1.1" 200 12
INFO 2024-02-20 11:18:51,481 "GET / HTTP/1.1" 200 12
INFO 2024-02-20 11:18:52,228 "GET /author/author_form/ HTTP/1.1" 200 1188
INFO 2024-02-20 11:44:56,639 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:44:58,525 Watching for file changes with StatReloader
INFO 2024-02-20 11:49:02,759 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:49:03,935 Watching for file changes with StatReloader
INFO 2024-02-20 11:49:23,104 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:49:25,068 Watching for file changes with StatReloader
INFO 2024-02-20 11:50:02,648 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:50:03,773 Watching for file changes with StatReloader
INFO 2024-02-20 11:50:11,279 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:50:12,152 Watching for file changes with StatReloader
INFO 2024-02-20 11:50:23,348 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:50:24,420 Watching for file changes with StatReloader
INFO 2024-02-20 11:51:51,667 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:51:52,620 Watching for file changes with StatReloader
INFO 2024-02-20 11:52:06,899 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:52:07,676 Watching for file changes with StatReloader
INFO 2024-02-20 11:52:21,901 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:52:22,602 Watching for file changes with StatReloader
INFO 2024-02-20 11:52:39,703 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:52:40,382 Watching for file changes with StatReloader
INFO 2024-02-20 11:53:46,713 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:53:47,682 Watching for file changes with StatReloader
INFO 2024-02-20 11:55:28,417 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:55:29,585 Watching for file changes with StatReloader
INFO 2024-02-20 11:56:04,134 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:56:04,931 Watching for file changes with StatReloader
INFO 2024-02-20 11:56:12,151 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:56:13,203 Watching for file changes with StatReloader
INFO 2024-02-20 11:56:42,453 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 11:56:43,596 Watching for file changes with StatReloader
INFO 2024-02-20 12:02:31,696 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 12:02:33,245 Watching for file changes with StatReloader
INFO 2024-02-20 12:31:15,298 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 12:31:16,242 Watching for file changes with StatReloader
INFO 2024-02-20 12:32:03,958 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 12:32:05,310 Watching for file changes with StatReloader
INFO 2024-02-20 12:34:54,363 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 12:34:55,158 Watching for file changes with StatReloader
INFO 2024-02-20 12:53:24,022 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 12:53:24,907 Watching for file changes with StatReloader
INFO 2024-02-20 12:55:03,352 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 12:55:04,652 Watching for file changes with StatReloader
INFO 2024-02-20 12:55:09,302 Watching for file changes with StatReloader
INFO 2024-02-20 12:56:40,096 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-20 12:56:41,225 Watching for file changes with StatReloader
INFO 2024-02-20 12:57:00,970 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/urls.py changed, reloading.
INFO 2024-02-20 12:57:02,523 Watching for file changes with StatReloader
INFO 2024-02-20 13:02:27,034 "GET / HTTP/1.1" 200 12
INFO 2024-02-20 13:02:31,295 "GET / HTTP/1.1" 200 12
INFO 2024-02-20 13:02:33,511 "GET / HTTP/1.1" 200 12
INFO 2024-02-20 13:02:34,898 "GET /post HTTP/1.1" 301 0
INFO 2024-02-20 13:02:35,020 "GET /post/ HTTP/1.1" 200 1973
INFO 2024-02-20 13:11:19,298 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/models.py changed, reloading.
INFO 2024-02-20 13:11:20,879 Watching for file changes with StatReloader
INFO 2024-02-20 13:11:22,718 "GET /post/ HTTP/1.1" 200 1805
INFO 2024-02-20 13:11:55,627 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 13:11:56,575 Watching for file changes with StatReloader
INFO 2024-02-20 13:11:58,288 "GET /post/ HTTP/1.1" 200 1641
ERROR 2024-02-20 13:35:18,071 Internal Server Error: /post/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 42, in post_form
    views_count=data['views_count'],
KeyError: 'views_count'
ERROR 2024-02-20 13:35:18,073 "POST /post/ HTTP/1.1" 500 61309
INFO 2024-02-20 13:35:38,979 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 13:35:39,787 Watching for file changes with StatReloader
INFO 2024-02-20 13:35:48,357 Watching for file changes with StatReloader
INFO 2024-02-20 13:35:56,616 "POST /post/ HTTP/1.1" 302 0
INFO 2024-02-20 13:35:56,711 "GET /post/ HTTP/1.1" 200 1641
INFO 2024-02-20 13:47:07,474 "GET /post/ HTTP/1.1" 200 1641
INFO 2024-02-20 13:47:11,444 "GET /posts/post/2 HTTP/1.1" 301 0
INFO 2024-02-20 13:47:11,487 "GET /posts/post/2/ HTTP/1.1" 200 19720
INFO 2024-02-20 13:49:40,237 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 13:49:41,306 Watching for file changes with StatReloader
INFO 2024-02-20 13:51:18,861 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 13:51:19,990 Watching for file changes with StatReloader
INFO 2024-02-20 13:51:40,293 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/forms.py changed, reloading.
INFO 2024-02-20 13:51:41,193 Watching for file changes with StatReloader
INFO 2024-02-20 13:53:56,988 "GET /posts/post/2/ HTTP/1.1" 200 19510
INFO 2024-02-20 14:00:27,448 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:00:28,615 Watching for file changes with StatReloader
INFO 2024-02-20 14:01:06,431 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:01:07,661 Watching for file changes with StatReloader
INFO 2024-02-20 14:02:33,676 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:02:34,791 Watching for file changes with StatReloader
INFO 2024-02-20 14:03:56,356 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:03:57,138 Watching for file changes with StatReloader
INFO 2024-02-20 14:06:04,432 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/models.py changed, reloading.
INFO 2024-02-20 14:06:05,889 Watching for file changes with StatReloader
INFO 2024-02-20 14:06:48,305 Watching for file changes with StatReloader
INFO 2024-02-20 14:08:03,397 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:08:04,566 Watching for file changes with StatReloader
INFO 2024-02-20 14:08:17,309 "GET /posts/post/2/ HTTP/1.1" 200 19510
INFO 2024-02-20 14:09:14,880 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:09:15,708 Watching for file changes with StatReloader
INFO 2024-02-20 14:09:30,991 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:09:32,003 Watching for file changes with StatReloader
INFO 2024-02-20 14:09:37,196 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:09:38,594 Watching for file changes with StatReloader
INFO 2024-02-20 14:11:12,818 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:11:14,032 Watching for file changes with StatReloader
INFO 2024-02-20 14:12:03,301 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:12:04,266 Watching for file changes with StatReloader
INFO 2024-02-20 14:12:26,746 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:12:27,685 Watching for file changes with StatReloader
INFO 2024-02-20 14:13:02,522 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:13:03,562 Watching for file changes with StatReloader
INFO 2024-02-20 14:13:06,232 "GET /posts/post/2/ HTTP/1.1" 200 20217
INFO 2024-02-20 14:14:03,196 "POST /posts/post/2/ HTTP/1.1" 200 21018
INFO 2024-02-20 14:17:41,838 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:17:42,654 Watching for file changes with StatReloader
INFO 2024-02-20 14:17:49,531 "POST /posts/post/2/ HTTP/1.1" 200 20392
INFO 2024-02-20 14:18:10,871 "POST /posts/post/2/ HTTP/1.1" 200 20553
INFO 2024-02-20 14:18:13,493 "POST /posts/post/2/ HTTP/1.1" 200 20714
INFO 2024-02-20 14:19:48,186 "POST /posts/post/2/ HTTP/1.1" 200 20879
INFO 2024-02-20 14:20:25,226 "POST /posts/post/2/ HTTP/1.1" 200 21038
INFO 2024-02-20 14:21:21,811 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:21:22,780 Watching for file changes with StatReloader
INFO 2024-02-20 14:21:52,191 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:21:53,339 Watching for file changes with StatReloader
ERROR 2024-02-20 14:21:54,760 Internal Server Error: /posts/post/2/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 25, in author_post
    redirect('author_post')
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'author_post' with no arguments not found. 1 pattern(s) tried: ['posts/post/(?P<post_id>[0-9]+)/\\Z']
ERROR 2024-02-20 14:21:54,762 "POST /posts/post/2/ HTTP/1.1" 500 81944
INFO 2024-02-20 14:22:19,064 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:22:20,950 Watching for file changes with StatReloader
INFO 2024-02-20 14:22:22,639 "GET /posts/post/2/ HTTP/1.1" 200 21185
INFO 2024-02-20 14:22:39,240 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:22:40,411 Watching for file changes with StatReloader
INFO 2024-02-20 14:22:41,910 "GET /posts/post/2/ HTTP/1.1" 200 21185
INFO 2024-02-20 14:22:43,407 "GET /posts/post/2/ HTTP/1.1" 200 21185
ERROR 2024-02-20 14:22:48,549 Internal Server Error: /posts/post/2/
Traceback (most recent call last):
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py", line 25, in author_post
    redirect('author_post')
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/pavelvatsek/PycharmProjects/DjangoSeminars/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'author_post' with no arguments not found. 1 pattern(s) tried: ['posts/post/(?P<post_id>[0-9]+)/\\Z']
ERROR 2024-02-20 14:22:48,550 "POST /posts/post/2/ HTTP/1.1" 500 81969
INFO 2024-02-20 14:25:02,181 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:25:03,571 Watching for file changes with StatReloader
INFO 2024-02-20 14:25:05,142 "POST /posts/post/2/ HTTP/1.1" 200 21494
INFO 2024-02-20 14:25:06,868 "POST /posts/post/2/ HTTP/1.1" 200 21646
INFO 2024-02-20 14:25:13,759 "POST /posts/post/2/ HTTP/1.1" 200 21790
INFO 2024-02-20 14:25:21,312 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/views.py changed, reloading.
INFO 2024-02-20 14:25:22,153 Watching for file changes with StatReloader
INFO 2024-02-20 14:25:24,257 "POST /posts/post/2/ HTTP/1.1" 302 0
INFO 2024-02-20 14:25:25,960 "GET /posts/post/2/ HTTP/1.1" 200 21937
INFO 2024-02-20 14:25:30,396 "POST /posts/post/2/ HTTP/1.1" 302 0
INFO 2024-02-20 14:25:30,445 "GET /posts/post/2/ HTTP/1.1" 200 22087
INFO 2024-02-20 14:25:39,927 "POST /posts/post/2/ HTTP/1.1" 302 0
INFO 2024-02-20 14:25:39,979 "GET /posts/post/2/ HTTP/1.1" 200 22242
INFO 2024-02-22 19:10:21,772 Watching for file changes with StatReloader
INFO 2024-02-22 19:10:24,052 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-02-22 19:10:24,252 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
INFO 2024-02-22 19:10:31,962 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-02-22 19:10:32,040 "GET /admin/ HTTP/1.1" 200 5533
INFO 2024-02-22 19:11:00,876 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/django_seminars/settings.py changed, reloading.
INFO 2024-02-22 19:11:03,882 Watching for file changes with StatReloader
INFO 2024-02-22 19:11:05,393 "GET /admin/ HTTP/1.1" 200 5944
INFO 2024-02-22 19:12:05,649 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 19:12:07,720 Watching for file changes with StatReloader
INFO 2024-02-22 19:14:24,154 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 19:14:26,095 Watching for file changes with StatReloader
INFO 2024-02-22 19:14:28,070 "GET /admin/ HTTP/1.1" 200 7481
INFO 2024-02-22 19:14:35,359 Watching for file changes with StatReloader
INFO 2024-02-22 19:14:38,314 "GET /admin/ HTTP/1.1" 200 7481
INFO 2024-02-22 19:16:00,964 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/admin.py changed, reloading.
INFO 2024-02-22 19:16:02,488 Watching for file changes with StatReloader
INFO 2024-02-22 19:16:20,172 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/randomapp/admin.py changed, reloading.
INFO 2024-02-22 19:16:21,270 Watching for file changes with StatReloader
INFO 2024-02-22 19:16:26,882 "GET /admin/ HTTP/1.1" 200 8174
INFO 2024-02-22 19:20:05,407 "GET /admin/auth/group/ HTTP/1.1" 200 9459
INFO 2024-02-22 19:20:05,459 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:20:09,024 "GET /admin/auth/group/add/ HTTP/1.1" 200 14777
INFO 2024-02-22 19:20:09,091 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:20:09,097 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15492
INFO 2024-02-22 19:20:09,279 "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
INFO 2024-02-22 19:20:09,285 "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
INFO 2024-02-22 19:23:16,130 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2024-02-22 19:23:16,168 "GET /admin/auth/group/ HTTP/1.1" 200 11200
INFO 2024-02-22 19:23:16,204 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:23:19,228 "GET /admin/auth/group/add/ HTTP/1.1" 200 14777
INFO 2024-02-22 19:23:19,245 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:25:41,814 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2024-02-22 19:25:41,866 "GET /admin/auth/group/ HTTP/1.1" 200 11534
INFO 2024-02-22 19:25:41,897 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:25:50,843 "GET /admin/auth/group/add/ HTTP/1.1" 200 14777
INFO 2024-02-22 19:25:50,866 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:27:34,300 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2024-02-22 19:27:34,335 "GET /admin/auth/group/add/ HTTP/1.1" 200 15070
INFO 2024-02-22 19:27:34,392 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:27:48,264 "GET /admin/auth/group/ HTTP/1.1" 200 11653
INFO 2024-02-22 19:27:48,303 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:27:54,409 "GET /admin/auth/group/add/ HTTP/1.1" 200 14777
INFO 2024-02-22 19:27:54,435 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:28:08,922 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2024-02-22 19:28:08,963 "GET /admin/auth/group/ HTTP/1.1" 200 12217
INFO 2024-02-22 19:28:08,995 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:28:24,555 "GET /admin/auth/group/add/ HTTP/1.1" 200 14777
INFO 2024-02-22 19:28:24,574 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:29:02,912 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2024-02-22 19:29:02,951 "GET /admin/auth/group/add/ HTTP/1.1" 200 15069
INFO 2024-02-22 19:29:03,005 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:29:26,984 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2024-02-22 19:29:27,017 "GET /admin/auth/group/ HTTP/1.1" 200 12893
INFO 2024-02-22 19:29:27,052 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:29:34,792 "GET /admin/auth/user/ HTTP/1.1" 200 14239
INFO 2024-02-22 19:29:34,856 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:29:39,448 "GET /admin/auth/user/add/ HTTP/1.1" 200 12914
INFO 2024-02-22 19:29:39,487 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:33:09,138 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/django_seminars/settings.py changed, reloading.
INFO 2024-02-22 19:33:10,028 Watching for file changes with StatReloader
INFO 2024-02-22 19:33:28,028 "POST /admin/auth/user/add/ HTTP/1.1" 200 13012
INFO 2024-02-22 19:33:28,124 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:34:13,573 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/django_seminars/settings.py changed, reloading.
INFO 2024-02-22 19:34:15,024 Watching for file changes with StatReloader
INFO 2024-02-22 19:34:21,577 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2024-02-22 19:34:21,842 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 25915
INFO 2024-02-22 19:34:21,969 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:34:22,367 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2024-02-22 19:34:22,368 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2024-02-22 19:35:15,092 "GET /admin/auth/group/ HTTP/1.1" 200 12673
INFO 2024-02-22 19:35:15,119 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:35:22,072 "GET /admin/auth/group/6/change/ HTTP/1.1" 200 15062
INFO 2024-02-22 19:35:22,112 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:35:35,257 "POST /admin/auth/group/6/change/ HTTP/1.1" 302 0
INFO 2024-02-22 19:35:35,288 "GET /admin/auth/group/ HTTP/1.1" 200 12877
INFO 2024-02-22 19:35:35,320 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:35:36,462 "GET /admin/auth/group/6/change/ HTTP/1.1" 200 15038
INFO 2024-02-22 19:35:36,495 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:35:43,405 "GET /admin/auth/group/ HTTP/1.1" 200 12661
INFO 2024-02-22 19:35:43,430 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:35:47,311 "GET /admin/auth/group/4/change/ HTTP/1.1" 200 15053
INFO 2024-02-22 19:35:47,349 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:35:51,948 "POST /admin/auth/group/4/change/ HTTP/1.1" 302 0
INFO 2024-02-22 19:35:51,981 "GET /admin/auth/group/ HTTP/1.1" 200 12868
INFO 2024-02-22 19:35:52,016 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:35:57,838 "GET /admin/auth/user/ HTTP/1.1" 200 14731
INFO 2024-02-22 19:35:57,880 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:35:59,254 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 25606
INFO 2024-02-22 19:35:59,283 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:36:43,948 "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2024-02-22 19:36:43,991 "GET /admin/auth/user/ HTTP/1.1" 200 14953
INFO 2024-02-22 19:36:44,045 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:36:46,852 "GET /admin/auth/user/add/ HTTP/1.1" 200 12615
INFO 2024-02-22 19:36:46,886 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:36:55,554 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2024-02-22 19:36:55,721 "GET /admin/auth/user/3/change/ HTTP/1.1" 200 25904
INFO 2024-02-22 19:36:55,793 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:37:49,685 "POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
INFO 2024-02-22 19:37:49,712 "GET /admin/auth/user/add/ HTTP/1.1" 200 12908
INFO 2024-02-22 19:37:49,818 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:37:56,903 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2024-02-22 19:37:56,965 "GET /admin/auth/user/4/change/ HTTP/1.1" 200 25904
INFO 2024-02-22 19:37:57,009 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:41:44,104 "POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
INFO 2024-02-22 19:41:44,322 "GET /admin/auth/user/ HTTP/1.1" 200 15959
INFO 2024-02-22 19:41:44,405 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:41:47,723 "POST /admin/logout/ HTTP/1.1" 200 3817
INFO 2024-02-22 19:41:51,028 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-02-22 19:41:51,054 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
INFO 2024-02-22 19:41:58,150 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-02-22 19:41:58,189 "GET /admin/ HTTP/1.1" 200 6722
INFO 2024-02-22 19:42:06,249 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/django_seminars/settings.py changed, reloading.
INFO 2024-02-22 19:42:08,338 Watching for file changes with StatReloader
INFO 2024-02-22 19:42:15,589 "GET /admin/blog/author/ HTTP/1.1" 200 8917
INFO 2024-02-22 19:42:21,241 "GET /admin/blog/comment/ HTTP/1.1" 200 18836
INFO 2024-02-22 19:42:24,752 "GET /admin/blog/post/ HTTP/1.1" 200 9279
INFO 2024-02-22 19:42:35,051 "POST /admin/logout/ HTTP/1.1" 200 3817
INFO 2024-02-22 19:42:37,017 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-02-22 19:42:37,069 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
INFO 2024-02-22 19:42:41,804 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-02-22 19:42:41,991 "GET /admin/ HTTP/1.1" 200 11879
INFO 2024-02-22 19:50:17,749 "GET /admin/blog/author/ HTTP/1.1" 200 13719
INFO 2024-02-22 19:50:17,787 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:50:22,575 "GET /admin/blog/author/ HTTP/1.1" 200 13719
INFO 2024-02-22 19:50:22,591 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:50:26,850 "GET /admin/blog/comment/ HTTP/1.1" 200 46079
INFO 2024-02-22 19:50:26,902 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:50:28,049 "GET /admin/blog/post/ HTTP/1.1" 200 14471
INFO 2024-02-22 19:50:28,083 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:50:28,904 "GET /admin/blog/author/ HTTP/1.1" 200 13719
INFO 2024-02-22 19:50:28,920 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:57:00,685 "GET /admin/blog/author/ HTTP/1.1" 200 14199
INFO 2024-02-22 19:57:00,701 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:59:20,756 "GET /admin/blog/comment/ HTTP/1.1" 200 46079
INFO 2024-02-22 19:59:20,794 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:59:21,689 "GET /admin/blog/post/ HTTP/1.1" 200 14471
INFO 2024-02-22 19:59:21,756 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 19:59:24,880 "GET /admin/blog/author/ HTTP/1.1" 200 14199
INFO 2024-02-22 19:59:24,918 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:00:15,975 "GET /admin/blog/author/ HTTP/1.1" 200 14199
INFO 2024-02-22 20:00:16,003 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:02:28,750 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:02:31,829 Watching for file changes with StatReloader
INFO 2024-02-22 20:03:00,055 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:03:01,026 Watching for file changes with StatReloader
INFO 2024-02-22 20:03:10,085 "GET /admin/blog/author/ HTTP/1.1" 200 16216
INFO 2024-02-22 20:03:10,137 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:14:26,618 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:14:30,475 Watching for file changes with StatReloader
INFO 2024-02-22 20:14:40,082 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:14:41,151 Watching for file changes with StatReloader
INFO 2024-02-22 20:14:44,400 "GET /admin/blog/author/ HTTP/1.1" 200 17203
INFO 2024-02-22 20:14:44,437 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:16:25,875 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:16:28,476 Watching for file changes with StatReloader
INFO 2024-02-22 20:18:02,193 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:18:03,368 Watching for file changes with StatReloader
INFO 2024-02-22 20:18:14,488 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:18:15,194 Watching for file changes with StatReloader
INFO 2024-02-22 20:18:21,485 "GET /admin/blog/author/ HTTP/1.1" 200 17203
INFO 2024-02-22 20:18:21,515 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:18:24,283 "GET /admin/blog/post/ HTTP/1.1" 200 15271
INFO 2024-02-22 20:18:24,340 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:20:31,989 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:20:32,835 Watching for file changes with StatReloader
INFO 2024-02-22 20:20:43,166 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:20:43,920 Watching for file changes with StatReloader
INFO 2024-02-22 20:20:56,646 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:20:58,372 Watching for file changes with StatReloader
INFO 2024-02-22 20:20:59,827 "GET /admin/blog/post/ HTTP/1.1" 200 17479
INFO 2024-02-22 20:21:00,142 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:22:05,094 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:22:06,193 Watching for file changes with StatReloader
INFO 2024-02-22 20:22:18,944 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:22:19,829 Watching for file changes with StatReloader
INFO 2024-02-22 20:22:40,620 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:22:41,529 Watching for file changes with StatReloader
INFO 2024-02-22 20:22:46,167 "GET /admin/blog/comment/ HTTP/1.1" 200 71120
INFO 2024-02-22 20:22:46,217 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:24:20,627 "GET /admin/blog/post/ HTTP/1.1" 200 17479
INFO 2024-02-22 20:24:20,714 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:24:21,827 "GET /admin/blog/comment/ HTTP/1.1" 200 71120
INFO 2024-02-22 20:24:21,866 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:24:56,554 "GET /admin/blog/comment/120/change/ HTTP/1.1" 200 15046
INFO 2024-02-22 20:24:56,598 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:29:26,974 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:29:28,196 Watching for file changes with StatReloader
INFO 2024-02-22 20:29:46,166 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:29:47,415 Watching for file changes with StatReloader
INFO 2024-02-22 20:29:51,058 "GET /admin/blog/comment/120/change/ HTTP/1.1" 200 15046
INFO 2024-02-22 20:29:51,666 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:30:29,929 "GET /admin/blog/comment/120/change/ HTTP/1.1" 200 15046
INFO 2024-02-22 20:30:30,005 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:30:34,503 "GET /admin/blog/author/ HTTP/1.1" 200 17203
INFO 2024-02-22 20:30:34,540 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:30:35,900 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 11717
INFO 2024-02-22 20:30:35,945 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:30:41,861 "POST /admin/blog/author/11/change/ HTTP/1.1" 302 0
INFO 2024-02-22 20:30:41,909 "GET /admin/blog/author/ HTTP/1.1" 200 17425
INFO 2024-02-22 20:30:41,954 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:30:44,016 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 11717
INFO 2024-02-22 20:30:44,054 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:31:57,043 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:31:58,221 Watching for file changes with StatReloader
INFO 2024-02-22 20:32:23,483 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:32:24,808 Watching for file changes with StatReloader
INFO 2024-02-22 20:32:28,146 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 13145
INFO 2024-02-22 20:32:28,172 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:39:02,529 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:39:03,857 Watching for file changes with StatReloader
INFO 2024-02-22 20:39:52,085 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:39:53,759 Watching for file changes with StatReloader
INFO 2024-02-22 20:39:55,318 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 13306
INFO 2024-02-22 20:39:55,817 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:41:38,949 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:41:40,090 Watching for file changes with StatReloader
INFO 2024-02-22 20:41:46,202 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:41:47,475 Watching for file changes with StatReloader
INFO 2024-02-22 20:41:49,905 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 13313
INFO 2024-02-22 20:41:50,011 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:42:44,914 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:42:45,848 Watching for file changes with StatReloader
INFO 2024-02-22 20:44:21,015 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:44:22,065 Watching for file changes with StatReloader
INFO 2024-02-22 20:44:27,447 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 13310
INFO 2024-02-22 20:44:27,480 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:44:28,546 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 13310
INFO 2024-02-22 20:44:28,680 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:45:19,185 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:45:20,152 Watching for file changes with StatReloader
INFO 2024-02-22 20:45:46,084 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:45:47,438 Watching for file changes with StatReloader
INFO 2024-02-22 20:45:49,849 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 13372
INFO 2024-02-22 20:45:49,958 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:55:01,243 "GET /admin/blog/author/ HTTP/1.1" 200 17203
INFO 2024-02-22 20:55:01,342 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:55:03,459 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 13372
INFO 2024-02-22 20:55:03,515 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:55:30,655 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:55:32,456 Watching for file changes with StatReloader
INFO 2024-02-22 20:55:33,907 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 14045
INFO 2024-02-22 20:55:33,963 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:55:38,892 "GET /admin/blog/author/ HTTP/1.1" 200 17203
INFO 2024-02-22 20:55:38,929 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:56:03,818 /Users/pavelvatsek/PycharmProjects/DjangoSeminars/django_seminars/blog/admin.py changed, reloading.
INFO 2024-02-22 20:56:04,695 Watching for file changes with StatReloader
INFO 2024-02-22 20:56:07,170 "GET /admin/blog/author/ HTTP/1.1" 200 17973
INFO 2024-02-22 20:56:07,192 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:56:13,690 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 13372
INFO 2024-02-22 20:56:13,713 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:56:22,100 "POST /admin/blog/author/11/change/ HTTP/1.1" 302 0
INFO 2024-02-22 20:56:22,154 "GET /admin/blog/author/ HTTP/1.1" 200 18199
INFO 2024-02-22 20:56:22,208 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:56:26,459 "GET /admin/blog/author/11/change/ HTTP/1.1" 200 13376
INFO 2024-02-22 20:56:26,479 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-22 20:56:34,377 "POST /admin/blog/author/11/change/ HTTP/1.1" 302 0
INFO 2024-02-22 20:56:34,428 "GET /admin/blog/author/ HTTP/1.1" 200 18195
INFO 2024-02-22 20:56:34,470 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-23 10:10:13,407 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2024-02-23 10:25:10,270 "GET / HTTP/1.1" 200 12
WARNING 2024-02-23 10:25:10,477 Not Found: /favicon.ico
WARNING 2024-02-23 10:25:10,479 "GET /favicon.ico HTTP/1.1" 404 3134
INFO 2024-02-23 13:22:32,187 Watching for file changes with StatReloader
INFO 2024-02-23 13:22:38,940 "POST /admin/logout/ HTTP/1.1" 302 0
INFO 2024-02-23 13:22:38,955 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-02-23 13:22:39,009 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
INFO 2024-02-23 13:22:43,933 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-02-23 13:22:43,981 "GET /admin/ HTTP/1.1" 200 11901
INFO 2024-02-23 13:22:50,179 "GET /admin/auth/group/ HTTP/1.1" 200 12651
INFO 2024-02-23 13:22:50,203 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-23 13:22:54,729 "GET /admin/auth/group/5/change/ HTTP/1.1" 200 15110
INFO 2024-02-23 13:22:54,773 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-23 13:22:58,243 "GET /admin/auth/group/3/change/ HTTP/1.1" 200 15087
INFO 2024-02-23 13:22:58,293 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-02-23 13:23:12,871 "GET /admin/ HTTP/1.1" 200 11901
INFO 2024-02-23 13:23:15,023 "POST /admin/logout/ HTTP/1.1" 200 3817
